acjvone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^', include('carsys.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))
"""

carsys/urls.py
from django.conf.urls import url
from django.contrib import admin
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'carsys'

urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^signup/$', views.Signup.as_view(), name='signup'),
    url(r'^addcar/$', views.AddCar.as_view(), name='addcar'),
    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^logout/$', views.Logout.as_view(), name='logout'),
    url(r'^caron/$', views.Caron.as_view(), name='caron'),
    url(r'^caroff/$', views.Caroff.as_view(), name='caroff'),
    url(r'^proflist/$', views.ProfileList.as_view(), name='proflist'),
    url(r'^profdetail/$', views.ProfileDetail.as_view(), name='proflistdet'),
    url(r'^carlist/$', views.CarList.as_view(), name='carlist'),
    url(r'^cardetail/$', views.CarDetail.as_view(), name='carlistdet'),
    url(r'^auth/$', views.Auth.as_view(), name='auth'),
    url(r'^userdata/$', views.UserData.as_view(), name='userdata'),
    url(r'^userinfo/$', views.UserInfo.as_view(), name='userinfo'),
    url(r'^userdetail/$', views.UserDetail.as_view(), name='userdetail'),
    url(r'^addreport/$', views.AddReport.as_view(), name='addrep'),
    url(r'^changecarstat/$', views.ChangeCarStat.as_view(), name='changecarstat'),
    url(r'^carloc/$', views.CarLocation.as_view(), name='carloc'),
    url(r'^carphoto/$', views.CarPhoto.as_view(), name='carphoto'),
    url(r'^carlocs/$', views.CarLocations.as_view(), name='carlocs'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

carsys/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(User):
	address = models.CharField(max_length=100)
	license_id = models.CharField(max_length=100)
	#check whether field can have INTEGER instead of CHAR
	contact_no = models.CharField(max_length=250)
	def __str__(self):
		return self.first_name + ' ' + self.last_name

class Car(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	plate_no = models.CharField(max_length=100)
	car_model = models.CharField(max_length=100)
	#true if stolen/carjacked false if not
	#on first car_stat true, send location
	car_stat = models.BooleanField(default=False)

	def __str__(self):
		return self.plate_no

class Report(models.Model):
	#we'll call all user info then get the user license ID to report
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	car_id = models.ForeignKey(Car, on_delete=models.CASCADE)
	#this column is for card ignition true for carstop false for not
	car_ignition = models.BooleanField(default=False)
	#taser can never be activated again unless there is change in report status
	taser_stat = models.BooleanField(default=False)
	#has the incident been reported or not?
	report_stat = models.BooleanField(default=False) 
	#this will show whether it was turned on or eventually turned off
	date_reported = models.DateTimeField(auto_now=True)
	#this is the location of the car
	car_loc = models.CharField(max_length=100)
	#when was location added?
	#car_loc_date = models.DateTimeField(auto_now_add=True)
  	#this is the probable thief of the car
  	#use reports.rep_person.url
	rep_photo = models.FileField()
	#when was photo added?
	#car_photo_date = models.DateTimeField(auto_now_add=True)
	#does user want location?
	car_loc_stat = models.BooleanField(default=False)
	#does user want photo?	
	car_photo_stat = models.BooleanField(default=False)

carsys/forms.py
from django import forms
from django.contrib.auth.models import User
#from .models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

 #ASK Suinan if you can make your own User model and how it works

carsys/views.py
# -*- coding: utf-8 -*-
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from rest_framework import status,generics
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from .serializers import *
from .forms import UserForm
from .models import *
from django.core.exceptions import ObjectDoesNotExist
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, Http404, JsonResponse
from datetime import datetime
import json

"""
START OF DJANGO REST
"""
# Create your views here.

class CarPhoto(APIView):
  
  def get(self,request):
    data={'acjcarsystem':'RPi gets reports'}
    return Response(data)

  def post(self, request,):
    #this is for adding new user
    plate_no = request.data['plate_no']
    if Car.objects.filter(plate_no=plate_no).exists():
      car = Car.objects.get(plate_no=plate_no)
      car_id=car.id
      car_stat = car.car_stat
      if Report.objects.filter(car_id=car_id).exclude(rep_photo="").exists():
        """if not Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[0].exists():
          report0=""
          date0=""
        else:"""
        try:
          report0=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[0].rep_photo
          date0=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[0].date_reported
        except IndexError:
          report0=""
          date0=""
        
        try:
          report1=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[1].rep_photo
          date1=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[1].date_reported
        except IndexError:
          report1=""
          date1=""
         
        try:
          report2=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[2].rep_photo
          date2=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[2].date_reported
        except IndexError:
          report2=""
          date2=""
        
        try:
          report3=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[3].rep_photo
          date3=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[3].date_reported
        except IndexError:
          report3=""
          date3=""
        

        try:
          report4=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[4].rep_photo
          date4=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[4].date_reported
        except IndexError:
          report4=""
          date4=""
        try:
          report5=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[5].rep_photo
          date5=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[5].date_reported
        except IndexError:
          report5=""
          date5=""
          
        try:
          report6=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[6].rep_photo
          date6=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[6].date_reported
        except IndexError:
          report6=""
          date6=""
        
        try:
          report7=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[7].rep_photo
          date7=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[7].date_reported
        except IndexError:
          report7=""
          date7=""
        
        
        try:
          report8=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[8].rep_photo
          date8=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[8].date_reported
        except IndexError:
          report8=""
          date8=""
        
        
        try:
          report9=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[9].rep_photo
          date9=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[9].date_reported
        except IndexError:
          report9=""
          date9=""
        
        print ('status is true')
        data = {}
        data['report0']=str(report0)
        data['date0']=str(date0)
        data['report1']=str(report1)
        data['date1']=str(date1)
        data['report2']=str(report2)
        data['date2']=str(date2)
        data['report3']=str(report3)
        data['date3']=str(date3)
        data['report4']=str(report4)
        data['date4']=str(date4)        
        data['report5']=str(report5)
        data['date5']=str(date5)        
        data['report6']=str(report6)
        data['date6']=str(date6)       
        data['report7']=str(report7)
        data['date7']=str(date7)        
        data['report8']=str(report8)
        data['date8']=str(date8)        
        data['report9']=str(report9)
        data['date9']=str(date9)
        data['Error']="False"

        return Response(data,)
      else:          
        data = {}
        data['car']=str(car)
        data['status']="No reports"
        data['Error']="True"
        return Response(data,)
    else:
      data = {}
      data['status']="No car"
      data['Error']="True"
      return Response(data,)
    return Response({'Error':'True'}, status=status.HTTP_400_BAD_REQUEST)

class CarLocations(APIView):
  #returns 10 locations
  def get(self,request):
    data={'acjcarsystem':'RPi gets reports'}
    return Response(data)

  def post(self, request,):
    #this is for adding new user
    plate_no = request.data['plate_no']
    if Car.objects.filter(plate_no=plate_no).exists():
      car = Car.objects.get(plate_no=plate_no)
      car_id=car.id
      car_stat = car.car_stat
      if Report.objects.filter(car_id=car_id).exclude(car_loc="").exists():
        """if not Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[0].exists():
          report0=""
          date0=""
        else:"""
        try:
          report0=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[0].car_loc
          date0=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[0].date_reported
        except IndexError:
          report0=""
          date0=""
        
        try:
          report1=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[1].car_loc
          date1=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[1].date_reported
        except IndexError:
          report1=""
          date1=""
         
        try:
          report2=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[2].car_loc
          date2=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[2].date_reported
        except IndexError:
          report2=""
          date2=""
        
        try:
          report3=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[3].car_loc
          date3=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[3].date_reported
        except IndexError:
          report3=""
          date3=""
        

        try:
          report4=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[4].car_loc
          date4=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[4].date_reported
        except IndexError:
          report4=""
          date4=""
        try:
          report5=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[5].car_loc
          date5=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[5].date_reported
        except IndexError:
          report5=""
          date5=""
          
        try:
          report6=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[6].car_loc
          date6=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[6].date_reported
        except IndexError:
          report6=""
          date6=""
        
        try:
          report7=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[7].car_loc
          date7=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[7].date_reported
        except IndexError:
          report7=""
          date7=""
        
        
        try:
          report8=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[8].car_loc
          date8=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[8].date_reported
        except IndexError:
          report8=""
          date8=""
        
        
        try:
          report9=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[9].car_loc
          date9=Report.objects.filter(car_id=car_id).exclude(rep_photo="").order_by('-date_reported')[9].date_reported
        except IndexError:
          report9=""
          date9=""
        
        print ('status is true')
        data = {}

carsys/templates/carsys/add_car.html
{% extends 'carsys/base.html' %}
{% block title %} Add Car {% endblock title %}
{% block body %}
<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            Plate No: <input type="text" name="plate_no"><br>
            Car Model: <input type="text" name="car_mo"><br>
                        
            <button type="submit" class="btn btn-success">Add Car</button>
</form>
{{key2}}
<p>Go back <a href="{% url 'carsys:index' %}">here</a>.</p>

{% endblock%}

carsys/templates/carsys/base.html
<html>
{% load static %}
<!DOCTYPE html>

<html lang="en-us">
<head>
    {% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="HandheldFriendly" content="true">
    {% endblock meta %}
    {% block add_meta %}
    {% endblock add_meta %}
    <title>
        {% block title %}    {% endblock title %}
    </title>

    {% block head_fonts %}
    <!-- font-awesome-icons -->
    <link href="{% static "css/font-awesome.css" %}" rel="stylesheet">
    <!-- //font-awesome-icons -->
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800" rel="stylesheet">
    {% endblock head_fonts %}

    {% block head_styles %}
    <!-- Bootstrap -->
<link rel="stylesheet" type="text/css"
    href="{% static 'vendor/bootstrap/3.3.6/css/bootstrap.min.css' %}">
<!-- Bootstrap Material theme -->
<link rel="stylesheet" type="text/css"
    href="{% static 'vendor/bootstrap/themes/material/0.5.9/css/bootstrap-material-design.min.css' %}">
<link rel="stylesheet" type="text/css"
    href="{% static 'vendor/bootstrap/themes/material/0.5.9/css/ripples.min.css' %}">
    
    {% endblock head_styles %}

    {% block head_scripts %}

    {% endblock head_scripts %}
</head>
{% block body %}

{% endblock %}

</html>

carsys/templates/carsys/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

carsys/templates/carsys/index.html
{% extends 'carsys/base.html' %}
{% block title %} Home {% endblock title %}
{% block body %}
<h2>dis index yay</h2>
<h2>{{ led }} </h2>
<h3>{{ user_data }} </h3>
{{log_stat}}
<form action="{% url 'carsys:logout' %}">
    <input type="submit" value="Logout" />
</form>

<form action="" method="post">
{% csrf_token %}
    {% for plate_no in q %}   
  <input type="radio" name="car" value="{{plate_no}}"
  >{{plate_no}}
  {% endfor %}</br>
  <input type="submit" value="Submit" />
</form>

{% if selected_car is not NONE %}
YOU SELECTED CAR <strong> {{ selected_car.plate_no }}</strong>
  {{ selected_car.user }}
  {{ selected_car.plate_no }}
  {{ selected_car.car_model }}
  {{ selected_car.car_stat }}

{% if selected_car.car_stat is False %}
<form action="{% url 'carsys:caron' %}"method="post">
{% csrf_token %}
    <input type="hidden" value="{{selected_car.plate_no}}" name='selcar' hidden/>
    <input type="submit" value="Turn Car {{selected_car.plate_no}} ON" />
</form>
{% endif %}
{% endif %}


{% if selected_car.car_stat and selected_car is not NONE %}
{{report}}
{{report.user}}
{{report.car_id}}
{{report.car_ignition}}
{{report.taser_stat}}
{{report.report_stat}}
{{report.car_loc_stat}}
{{report.car_photo_stat}}
<form action="{% url 'carsys:caroff' %}"method="post">
{% csrf_token %}
    <input type="checkbox" name="report" value="True" 
    {% if report.report_stat %}
    checked
    disabled="disabled"
    {% endif %}
    >Report? </br>
    <input type="checkbox" name="ignition" value="True" 
    {% if report.car_ignition %}
    checked
    {% endif %}
    >Ignition? </br>
    <input type="checkbox" name="taser" value="True" 
    {% if report.taser_stat %}
    checked
    disabled="disabled"
    {% endif %}
    >Taser? </br>
    <input type="checkbox" name="location" value="True" 
    {% if report.car_loc_stat %}
    checked
    {% endif %}
    >Determine Location? </br>
    <input type="checkbox" name="photo" value="True" 
    {% if report.car_photo_stat %}
    checked
    {% endif %}
    >Take Photo? </br>
    <input type="checkbox" name="carstem" value="False">Turn Off System? </br>


    <input type="hidden" value="{{selected_car.user}}" name='user' hidden/>
    <input type="hidden" value="{{selected_car.plate_no}}" name='selcar' hidden/>
    <input type="submit" value="I choose these options" />
</form>
{% endif %}


<p>Add car <a href="{% url 'carsys:addcar' %}">here</a>.</p>

{% endblock%}

carsys/templates/carsys/login.html
{% extends 'carsys/base.html' %}
{% block title %}Login{% endblock title %}
{% block body %}

<form role="form" action="{% url 'carsys:login' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!--{% include 'carsys/form_template.html' %}-->
            {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            Username: <input class="form-control" type="text" name="username"><br>
            Password: <input type="password" name="password"><br>
            <button type="submit" class="btn btn-success">Submit</button>
</form>

<p>Not yet registered? Register <a href="{% url 'carsys:signup' %}">here</a>.</p>

{% endblock %}

carsys/templates/carsys/signup.html
{% extends 'carsys/base.html' %}
{% block title %} Sign Up {% endblock %}
{% block body %}

<form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            Username: <input class="form-control" type="text" name="username" required><br>
            Password: <input type="password" name="password" required><br>
            First Name: <input type="text" name="f_name"><br>
            Last Name: <input type="text" name="l_name"><br>
            Address: <input type="text" name="address"><br>
            License ID: <input type="text" name="lic_ID"><br>
            Contact No: <input type="text" name="cont_no"><br>
            
            <p>{{ username }}</p>
            
            <button type="submit" class="btn btn-success">Submit</button>
</form>
<p>Have an account? Sign in <a href="{% url 'carsys:login' %}">here</a>.</p>

{% endblock %}